category = "Nonprofit tech"
description = "Constituent Relationship Management software helps organizations and movements maintain roles of their members, and often includes a suite of tools for managing those relationships."
name = "CRM"
