category = "Adjacent Fields"
description = "The ability to navigate technology and complicated digital contexts is an increasingly necessary skillset for citizens. Digitization of government, online advocacy campaigns, and other civic tech efforts will hit hard limits if the constituency or electorate isn't comfortable using technology."
name = "Digital literacy"
