category = "Adjacent Fields"
description = "We consider these categories necessary pre-requisites for effective civic tech. Without digital literacy and access, meaningful representation, trust and safety, or civic literacy, civic tech will not succeed. So while not every project in this section is explicitly 'civic tech', they are vital foundational layers to the field."
name = "Foundational layers"
