category = "Adjacent Fields"
description = "There's a rich ecosystem of related and overlapping fields with civic tech, including those that predate civic tech. People define the field with broader or more narrow scopes in mind, so here we track related work areas."
name = "Tech for public challenges"
