category = "Voting and elections"
description = "Third parties oversee elections to ensure they are run in a free and fair manner. For example, we must track ballot requests and submitted ballots to ensure voters' voices are heard."
name = "Election observation"
