category = "Voting and elections"
description = "Rather than build redundant resources outside of government, election administration tech works to empower and assist the people who are already responsible for running elections."
name = "Election administration"
