category = "Voting and elections"
description = "This class of civic tech tools and data services help voters find out where -- and often how and when -- to cast their vote. These tools are particularly helpful in the US, where rules, deadlines, and polling procedures may vary dramatically by state."
name = "Find your polling place"
