category = "Voting and elections"
description = "Apps and services to help voters access polling places, particularly in areas where vote suppressors have intentionally made the locations harder to access."
name = "Getting to the polls"
