category = "Voting and elections"
description = "Tools, resources, databases, and trainings to encourage a more representative group of people to run for office."
name = "Help more people run for office"
