category = "Voting and elections"
description = "Those looking to suppress the electorate from voting use myriad local laws and rules to discount ballots. These efforts help voters ensure their voice is heard, and not discounted for some procedural error."
name = "Make sure votes are counted"
