category = "Voting and elections"
description = "Research shows that voters are more likely to vote if they have a plan on what they need to do, logistically, on the day they cast their ballot. This genre of civic tech makes it easy for a voter to put together a plan that coincides with local election dates, deadlines, locations, and modalities."
name = "Make a plan to vote"
