category = "Voting and elections"
description = "One of the hallmarks of a democracy is that when the people choose to vote out the incumbent, they peacefully leave office."
name = "Peaceful transition of power"
