category = "Voting and elections"
description = "Tactical voting is when the electorate itself coordinates vote switching to cause or prevent a certain result. It only works in certain electoral systems."
name = "Tactical voting"
