category = "Mapping"
description = "Civic maps collect and display data geographically to coordinate action, plot resources, or make an argument for change. This is our gallery of specific civic maps."
name = "Civic maps"
