category = "Organize campaigns"
description = "Tech that helps people direct their money away from socially and environmentally destructive companies, or toward good ones. For example, scanner apps that link bar codes to producers' campaign donations, environmental footprints, or other proxies of note."
name = "Boycott or buycott"
