category = "Organize campaigns"
description = "A list of civic groups, organizations and movements that regularly launch and lead specific campaigns to make meaningful changes in our society."
name = "Campaign organizations"
