category = "Organize campaigns"
description = """
Social change work takes a high level of coordination. From email to WhatsApp and Slack to web conferencing, the tools we use to coordinate with each other, activists, members, volunteers and other stakeholders can help build and maintain alignment, operationalize the work, and connect a "nervous system” of collaborators."

- Adapted from Narrative Initiative"""
name = "Internal communication and coordination"
