category = "Organize campaigns"
description = "Large organizing campaigns have inspired new software products that facilitate onboarding, managing, and leading large networks of volunteers."
name = "Manage volunteers"
