category = "Organize campaigns"
description = """
This is our collection of discrete tech-supported campaigns designed to create a change in the world. A campaign is the method in which we organize people to shift power. Technology has changed how campaigns operate, for the better (it's never been easier or cheaper to reach and organize large numbers of people) and the worse (private data has been used to profile voters, and technology is accused of facilitating shallower relationships between supporters).

See also our <a href="https://civictech.guide/advocacy">campaign tools</a> collection or learn about <a href="https://civictech.guide/listing-category/campaign-orgs/">campaign organizations</a>."""
name = "Specific campaigns"
