category = "Academia"
description = "Collaborative research programs dedicated to investigate the relations between technology and civic engagement and other challenges around concepts like citizenship, participation, and democracy."
name = "Peer-reviewed research"
