category = "In-person meetings"
description = "Meetup counts over 100,000 members of 166 civic hacking meetups around the world. The groups included here vary in how technical they are, but you can always count on meeting people and contributing to projects, regardless of whether or not you can code."
name = "Civic hacking meetups"
