category = "In-person meetings"
description = "Community gathering spaces dedicated to civic tech that often provide coworking, meeting space, and other amenities like makerspaces, cafes, or theaters."
name = "Hubs"
