category = "In-person meetings"
description = "Roundtables are groups of people selected to weigh in on a central organizing topics. They may be public or closed invitation, and are usually organized to build conversation and connections between actors on a given topic, such as open government data."
name = "Roundtables"
