category = "In-person meetings"
description = "Working groups are formed to explore and often, consider the feasibility of an emerging topic or concern. For example, a working group might consider the balance between efficiency and privacy in a smart city project."
name = "Working groups"
