category = "In-person meetings"
description = "Do you want to learn how to use data to meet a challenge in your community? Are you interested in understanding more about concepts like power or citizen engagement? Check out these workshops and participate in the discussion."
name = "Workshops"
