display_name = "City & Local Government"
id = "city-local-government"
synonyms = [
  "311",
  "311 data",
  "311-data",
  "311 widget",
  "city",
  "city-budget",
  "city-chat",
  "city-council",
  "city-council-data",
  "city-government",
  "city planning",
  "city-press",
  "city statistics",
  "city-zoning",
  "complete-count-committee",
  "comptroller-nyc-gov",
  "councils",
  "counties",
  "county",
  "dataphilly",
  "fixmystreet",
  "local-government",
  "municipal-agendas",
  "municipalities",
  "municipality",
  "neighborhood",
  "neighborhood-councils",
  "neighborhood-map",
  "neighborhoods",
  "open311",
  "open-budgets",
  "open-contracting",
  "opengov",
  "open-government",
  "opengovernment",
  "puerto-rico-municipalities",
  "smart-cities",
  "smart-city"
]
