display_name = "Civic Tech"
id = "civic-tech"
synonyms = [
  "civic-apps",
  "civic-apps-team",
  "civic-data",
  "civic-hacking",
  "civic-infrastructure",
  "civic-innovation",
  "civic-tech",
  "civictech",
  "civictechindex",
  "civic-tech-index",
  "civic-tech-projects-catalog",
  "civic-tech-projects-index",
  "civic-tech-projects-map",
  "civic-tech-projects-volunteers",
  "civic-tech-puerto-rico",
  "civic-tech-taxonomy",
  "civil-tech",
  "govtech"
]
