display_name = "Civil & Social Rights"
id = "civil-social-rights"
synonyms = [
  "accessibility",
  "Accessiblilty",
  "aclu",
  "civil-rights",
  "Equality",
  "gender",
  "gender-equality",
  "gender-equity",
  "gender-gap",
  "gender-inclusive-language",
  "gender-neutral-language",
  "harassment",
  "harassment-monitor",
  "homeless",
  "Homelessness",
  "Inequality",
  "Inequality Anti-corporation",
  "lgbtq",
  "native-lands",
  "Seniors",
  "Social Good",
  "social impact",
  "Social Justice",
  "social-justice",
  "Social projects",
  "social-safety-net",
  "social-services",
  "social-sharing",
  "social-workers",
  "Women's Rights",
  "youth"
]
