display_name = "Civic & Community"
id = "civic-community"
synonyms = [
  "citizen-action",
  "civic-activists",
  "civic-apps",
  "civic-apps-team",
  "civic-artworks",
  "civic-data",
  "Civic Education",
  "CivicEngagement",
  "civic-hacking",
  "civic-infrastructure",
  "civic-innovation",
  "Civic involvement",
  "civic-tech",
  "civictech",
  "civictechindex",
  "civic-tech-puerto-rico",
  "civic-watchdog",
  "Communities",
  "community",
  "community-boards",
  "Community Development",
  "community-districts",
  "community-driven",
  "community-eligibility-provision",
  "community-engagement",
  "community-engagment",
  "Community Garden",
  "community-gardens",
  "community-groups",
  "community-organizing",
  "community-outreach",
  "community-project",
  "community-radio",
  "community-sourced"
]
