display_name = "Culture"
id = "culture"
synonyms = [
  "art",
  "artists",
  "arts",
  "arts and culture",
  "culture",
  "data-driven-journalism",
  "data-journalism",
  "digital-journalism",
  "Documentary",
  "Film",
  "gmmp",
  "graffiti",
  "huffington-post",
  "ilab",
  "journalism",
  "journalism-training",
  "journalist",
  "journalists",
  "Language",
  "Language Access",
  "library",
  "library-management-system",
  "media",
  "media-monitoring",
  "mural",
  "murals",
  "mural-tour-2021",
  "Music",
  "news",
  "newstools",
  "oakland-art-murmur",
  "Photography",
  "public-art",
  "theater",
  "theater-hub",
  "vegan"
]
