display_name = "Economy & Finance"
id = "economy"
synonyms = [
  "Anti-Corporate",
  "assessor-scaper",
  "assessors-website",
  "budget",
  "budget-app",
  "budgets",
  "checkbook-nyc",
  "economic development",
  "Economic Inequality",
  "equal-pay",
  "expenses",
  "fighting poverty",
  "Finance",
  "fiscaldata",
  "labor",
  "labour",
  "living-wage",
  "local economy",
  "money",
  "national-budget",
  "openbudget",
  "openbudgets",
  "open-spending",
  "participatory-budget",
  "property-taxes",
  "public-budget",
  "tax",
  "taxclock",
  "taxes",
  "tax-rate"
]
