display_name = "Health Care"
id = "healthcare"
synonyms = [
  "calorie-calculator",
  "Cancer",
  "cognoma",
  "disease-surveillance",
  "dodgy-doctors",
  "epidemics",
  "epidemiology",
  "health",
  "health-care",
  "healthcare",
  "health-resource",
  "healthtools",
  "healthtools-api",
  "healthtools-kenya-api",
  "hospital-services",
  "medicine-prices",
  "Opioid Crisis",
  "pandemic",
  "Public Health",
  "public-health",
  "Public Heath",
  "west-nile-virus"
]
