display_name = "Housing & Urban Planning"
id = "housing"
synonyms = [
  "help for homes",
  "housing",
  "housing-affordability",
  "housing-policies",
  "housing-policy",
  "renters",
  "shared-housing",
  "Urban housing"
]
