display_name = "Poverty"
id = "poverty"
synonyms = [
  "fighting poverty",
  "food-access",
  "food-deserts",
  "food donation",
  "food-insecure",
  "Food Insecurity",
  "food-pantry",
  "food-resources",
  "food-security",
  "free-food",
  "free-meals",
  "homeless",
  "Homelessness",
  "hunger",
  "living-wage",
  "poverty"
]
