category = "Participatory democracy"
description = "Perhaps the core premise of civic tech is that it can improve civic engagement. Whether in concert with formal governmental bodies or independent of them, civic tech promises to help citizens (in the Latin sense, of the city) engage with one another to share power in the pursuit of building just societies."
name = "Engagement tech"
