category = "Participatory democracy"
description = "Tools and platforms that aid group decision making through deliberate design decisions to improve the likelihood of desired outcomes, such as consensus."
name = "Group decision making"
