site_name: Civic Tech Taxonomy Docs
repo_url: https://github.com/codeforamerica/civic-tech-taxonomy
site_url: https://codeforamerica.github.io/civic-tech-taxonomy
edit_uri: edit/master/docs

theme:
  name: material
  features:
    - navigation.tabs
  palette:
    primary: "teal"
    accent: "amber"

plugins:
  - search
  - awesome-pages

extra_javascript:
  - https://unpkg.com/mermaid@8.5.0/dist/mermaid.min.js

extra_css:
  - https://use.fontawesome.com/releases/v5.13.0/css/all.css

markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.smartsymbols
  - meta
  - toc:
      # insert a blank space before the character
      permalink: " ¶"
  - smarty
  - fontawesome_markdown
  - mdx_truly_sane_lists
