category = "Engagement tech"
description = "Distributed resource-gathering campaigns facilitated by dedicated platforms. While many civic projects make use of mainstream crowdfunding platforms, other platforms focused explicitly on civic, urban, or social impact projects."
name = "Civic crowdfunding platforms"
