category = "Engagement tech"
description = "Embedding social good and civic engagement features into otherwise mainstream technology platforms. For example, helping users register to vote ahead of elections."
name = "Civic features"
