category = "Engagement tech"
description = "Interactive voice response (IVR) is a technology that bridges analog and digital experiences by allowing humans to interact with a computer through their voices and dialpad entries. It's used in many ICT4D projects where smartphone and desktop devices are not yet prevalent."
name = "Interactive Voice Response"
