category = "Engagement tech"
description = "Digital conversation hubs for conversations of civic import. They are often designed to facilitate constructive dialogues, but sometimes fail by attempting to creating new destinations rather than embrace existing community hubs."
name = "Online forums"
