category = "Engagement tech"
description = "Open innovation is the process of expanding the pool of innovators within an institution or organization through greater transparency, greater invitation to participate, creation or addition of low-barrier input channels, and similar mechanisms."
name = "Open innovation"
