category = "Engagement tech"
description = "Surveys are used to gather input, measure public opinion, and establish baseline understanding of demographics and other information about residents."
name = "Surveys"
