category = "Academic programs"
description = 'A new name for the field introduced by the Ford Foundation, Public Interest Tech "is an emerging scholarly and professional field that is defined by the deployment of technological expertise in service of the common good, often with a focus on under-resourced communities and needs." (definition from Cornell Tech)'
name = "Public Interest Tech"
