[gitsheet]
root = "taxonomies/statuses"
path = "${{ id }}"

[gitsheet.fields.id]
type = "string"

[gitsheet.fields.display_name]
type = "string"

[gitsheet.fields.synonyms]
type = "array"
items = { type = "string" }
sort = true
