category = "Watchdogging and transparency"
description = "Budget explorers help citizens understand where government funds -- and their tax contributions -- go. They're usually visual, and sometimes interactive, helping people become more literate in the budget-setting and expenditures process."
name = "Budget explorers"
