category = "Watchdogging and transparency"
description = 'Consumer watchdogging efforts use tech to bring transparency and accountability to private sector actors. See also <a href="https://civictech.guide/listing-category/brand-organizing/">brand organizing</a>, which are specific campaigns targeting corporate brands.'
name = "Consumer watchdogging"
