category = "Watchdogging and transparency"
description = "Efforts to track, visualize, share, and otherwise make public the story of interests lobbying for government influence. Or, projects that seek to make access to lobbying government more equitable and participatory."
name = "Lobbying"
