category = "Watchdogging and transparency"
description = "Promise trackers leverage tech to enunciate political promises (often made during the campaign period) and then audit the degree to which the politician or party has or hasn't fulfilled these promises while governing."
name = "Promise trackers"
