category = "Watchdogging and transparency"
description = "This section provides systematic analyses to evaluate promises made by governments and other institutions, track the performance of programs, initiatives, or projects. Are they working? How well?"
name = "Report cards and audits"
