category = "Watchdogging and transparency"
description = "Whistleblowing tech helps encourage and protect people who take great risks to expose illegal and unjust behavior to the press and/or the public."
name = "Whistleblowing"
