category = "Advocacy tech"
description = "How can you help? Where can you take action? These sites and wizards connect your desire to make an impact to active channels for participation."
name = "Activism aggregators"
