category = "Advocacy tech"
description = "Technologies that seek to provide greater visibility to the activities of governments, corporations, or individuals in power and allow others to monitor them."
name = "Watchdogging and transparency"
