category = "Campaign tools"
description = "These tools allow campaigns to call through supporter and potential supporter lists, and can also connect supporters through to targets, such as their representatives' legislative offices."
name = "Call campaign tools"
