category = "Campaign tools"
description = "Email is still the main driver of key actions, from petitions to fundraising to volunteer signups. This section includes tools for sending email campaigns that promote civic action."
name = "Email campaign tools"
