category = "Campaign tools"
description = "Online petition platforms symbolize many of the pros and cons of digital organizing: they can be used to amass huge amounts of support around an issue, but have been criticized as a tactic when groups use them to collect email addresses, rather than deliver change. Some online petitions are never delivered, and congressional staff are skeptical of the tactic."
name = "Petitions"
