category = "Campaign tools"
description = "SMS tools take advantage of the relatively high open rate and intimacy of messaging to reach people with information and calls to action."
name = "SMS campaign tools"
