category = "Foundational layers"
description = "The web and other technologies should be accessible to all people. The ability to use technology regardless of disability or status is a fundamental precursor to that technology serving civic goals."
name = "Assistive and Accessible Tech"
