category = "Foundational layers"
description = "If people cannot easily connect to digital tools in an equitable manner, civic tech will fail to address existing power imbalances in society"
name = "Connectivity"
