category = "Foundational layers"
description = "If civic tech is not built by and for a representative portion of society, it cannot hope to legitimately serve the public's needs"
name = "Diversity & Inclusion"
