category = "Foundational layers"
description = "A well governed open internet is critical to the practice of civic tech, particularly where power and technology collide."
name = "Internet governance"
