category = "Robotics"
description = '"Soft Robotics is the specific subfield of robotics dealing with constructing robots from highly compliant materials, similar to those found in living organisms. Soft robotics draws heavily from the way in which living organisms move and adapt to their surroundings." - Wikipedia https://en.wikipedia.org/wiki/Soft_robotics'
name = "Soft robotics"
