category = "Special coverage"
description = "Predecessors catalogs the projects and organizations that were historically important to the development of the field of civic tech."
name = "Predecessors"
