category = "Hardware"
description = "Using modern tools to model and fabricate products in novel ways, like 3D printing and  lasercutting, toward pro-social ends (like making face masks)"
name = "Digital fabrication"
