category = "Hardware"
description = "\"Unmanned aerial vehicles\" and other self-propelled flying machines when they're used for positive societal ends, like delivering medicine or capturing environmental imagery."
name = "Drones"
