category = "Hardware"
description = "Satellites can be used for a range of public good tech solutions, from providing imagery to humanitarian responses to monitoring environmental degradation."
name = "Satellites"
