category = "Communicating with the government"
description = "A subset of crowdsourced data collection, issue reporting platforms enable residents to notify their government(s) of items in need of attention, often municipal."
name = "Issue reporting"
