category = "Communicating with the government"
description = "Open ask platforms allow constituents to put a question to the government in a public way that others can see and co-sign. These platforms focus on making the governments' answers public as another form of transparency. In some contexts, asking the government for information on an ad hoc basis is the only way to open up data about certain topics."
name = "Open asks"
