category = "Emerging tech"
description = "Virtual Reality applied to increasing comprehension of public policies, driving empathy, understanding the effects of climate change, etc."
name = "Virtual and augmented reality"
