category = "Learn about civic tech"
description = "A list of books exploring different issues like how civic tech can be used to meet challenges in the cities,  how to increase democratic participation, or what are the best ways to combat ethical concerns."
name = "Books"
