category = "Learn about civic tech"
description = "Creative and innovative fiction projects exploring different issues related to civic tech. From tv programs to educate people about legal rights to documentaries and novels that explore social justice and civic imagination."
name = "Civic fiction"
