category = "Learn about civic tech"
description = "Projects employing speculative, forward-looking perspectives to envision what the future could look like, often to move us toward closer to an ideal state or to warn us away from a dystopia."
name = "Civic imagination"
