category = "Learn about civic tech"
description = "Glossaries are mini dictionaries that improve literacy in a specialized space. Civic tech glossaries help de-mystify the specialized language and acronyms often used to describe tech and civic work."
name = "Glossaries"
