category = "Learn about civic tech"
description = "News platforms and blogs that drive conversations around civic tech to promote debate, raise awareness, inform, analyze, or inspire people."
name = "News and blogs"
