category = "Media"
description = "Innovative approaches to advertising that drive awareness to underpromoted causes, or, alternatively, investigations into the power behind advertising money and platforms."
name = "Advertising"
