category = "Media"
description = 'Tools that insert diverse viewpoints to disrupt echo chambers on social media platforms or help people find common ground in person. These tools are often predicated on the beliefs that society has become more polarized, that social media has accelerated this trend, and that "both sides" should "meet in the middle", like by restoring some degree of collective media consumption.'
name = "Filter bubble poppers"
