category = "Media"
description = "Digital or analog games and activities designed to promote civic engagement and awareness through play. Many of the digital games are one-off projects, and aren’t maintained over long periods of time (for example, when browsers remove support for Adobe Flash). Gamification seeks to bring elements and mechanics of gameplay to more arduous tasks, like registering to vote."
name = "Games and gamification"
