category = "Media"
description = "Tools and datasets that allow us to quantify and study how an idea, meme, or campaign moves through the media ecosystem. This work is important to understanding why we’re talking about certain stories, considering how news events are framed by competing actors, and thinking about our news blindspots that leave us uninformed on entire topics or parts of the world."
name = "Media and social media analysis"
