category = "Media"
description = '"Narrative Technology encompasses the tools, platforms, and infrastructure that can be used to assist and accelerate the shifting and/or maintenance of dominant narratives. This includes technologies that can baseline, listen to, test, and respond to media and online discourse at scale." - The Narrative Initiative'
name = "Narrative tech"
