category = "Media"
description = "Working to break down barriers to intercultural communication, while ensuring indigenous and native languages are represented online and survive the transition to digital."
name = "Translation and linguistic representation"
