category = "Help out"
description = "Platforms that coordinate volunteer effort, including responses to natural disasters and pandemics as well as contributions to civic tech projects confronting systemic societal issues. Check out the opportunities on these platforms to get engaged."
name = "Pro bono and volunteer"
