description = "Although not always explicitly civic tech, these categories are directly adjacent, like tech for other shared, public challenges, or foundational layers that must be present for civic tech to succeed in its goals."
name = "Adjacent Fields"
