category = "Evaluate impact"
description = "Benchmarks are often used to evaluate projects. They may consist of a set of baseline data gathered from a cohort of related actors in a field. Knowing this baseline performance data allows project owners to reflect on their own impact in relation."
name = "Benchmarks"
