category = "Evaluate impact"
description = "Indicators are used to measure concrete progress towards larger goals. For example, the UN Sustainable Development Goals include 232 indicators to mark progress."
name = "Indicators"
