category = "The Tech"
description = "In the Civic Tech Field Guide, we focus on examples of govtech that seek to improve society to make it more just and democratic, not just more digital or efficient. We recognize that this is a subjective, values-based perspective of govtech. There is a much larger government IT industry, and we do not aspire to catalog and curate every instance of governmental technology."
name = "Govtech"
