category = "The Tech"
description = "Participatory democracy strives to create opportunities for all members of a population to make meaningful contributions to decision-making and seeks to broaden the range of people who have access to such opportunities. (Wikipedia: Participatory democracy)"
name = "Participatory democracy"
