category = "Bureaucracy tech"
description = "Documents, platforms, and tools to understand about regulation and how governments are responding to constant problems. You can also find some resources provided to encourage people’s presence in governance."
name = "Regulation"
