category = "Bureaucracy tech"
description = "Designing democratic government so that it can continue functioning if forced to govern remotely, as experienced during the COVID-19 social distancing."
name = "Remote government"
