category = "Artificial Intelligence"
description = "Autonomous or semi-autonomous chat agents that interact with people for the purpose of achieving a civic goal, like registering a vote or capturing citizen feedback."
name = "Bots"
