category = "Artificial Intelligence"
description = '"[A] set of coordinated government policies that have a clear objective of maximizing the potential benefits and minimizing the potential costs of AI for the economy and society" - Building an AI World, by CIFAR'
name = "Government AI strategies"
