category = "Find a job or hire someone"
description = "Find your fellowship in civic tech or a related field. We track over 40 paid and unpaid fellowships around the world. You can <a href=\"https://civictech.guide/submit-listing/\">share any fellowships we're missing here</a>."
name = "Fellowships"
