category = "Find a job or hire someone"
description = "These online platforms will let you see current job listings, and often allow you to filter by location, seniority level, and other factors."
name = "Job boards"
