category = "Govtech"
description = "How the government purchases products and services, including tech, makes a significant difference in the quality and value of the tech our governments operate."
name = "Procurement"
