category = "Govtech"
description = "Redesigning public service delivery, often from a Human Centered Design perspective rather than a government or bureaucracy perspective."
name = "Service delivery"
