category = "Govtech"
description = "Data and tools designed to help people vote by informing voters about registration requirements, ballot information, districts, and election dates, locations, and procedures."
name = "Voting and elections"
