category = "Build something"
description = "Explore accelerator programs that offer funding, training, and mentorship and connect people and experts that could work together to face hard challenges around the world."
name = "Accelerators"
