category = "Build something"
description = 'Centers, programs, organizations, and collectives dedicated to promoting innovation and social impact. You can also explore <a href="https://civictech.guide/listing-category/tech-companies-with-civic-teams/">Tech companies that have civic teams</a> and <a href="https://civictech.guide/listing-category/social-impact-design-groups/">social impact design firms</a>'
name = "Building in the private sector"
