category = "Build something"
description = "Civic &amp; social good hackathons facilitate people working together for a cause or a change. Developers, volunteers, entrepreneurs or tech enthusiasts are challenged to identify solutions while connecting with others and contributing to civic innovation."
name = "Civic hackathons"
