category = "Build something"
description = "Growth and mentorship are important aspects that could make a difference in the process of changing and creating impact. These incubators provide the resources needed to transform ideas into successful civic tech initiatives."
name = "Incubators"
