category = "Build something"
description = 'While there are many organizations with "Labs" in their name, this category refers explicitly to innovation units inside of larger organizations and institutions.'
name = "Innovation teams and labs"
