category = "Design"
description = "A collection of resources, methods, tools, and materials to facilitate participatory co-design practices and to help projects find the direction they need. Co-creation and open design techniques allow others to make creative contributions in the solution of a specific problem."
name = "Co-design"
