category = "Design"
description = "Designers will often capture their methods into 'playbooks', which are portable collections of options that others can pick up and adapt to their own context. Likewise, design principles establish core principles by which a given organization or office operates."
name = "Playbooks and design principles"
