category = "Ethical tech"
description = "The decentralization movement aims to limit the increasing centralization of the internet and digital resources into a small number of powerful platform companies. In doing so, they hope to promote free expression and resilience."
name = "Decentralization"
