category = "Ethical tech"
description = """
"[A]n ecosystem of ideas and practices that could bring into being [public sector] digital infrastructure that aligns with community aspirations, protects personal and group safety, and prioritizes people, communities, and a public good."

Advocates for digital public infrastructure make comparisons to the public sector funding of public interest outlets, such as public media, and argue that the internet would greatly benefit from a modern version of the same."""
name = "Digital Public Infrastructure"
