category = "Ethical tech"
description = "Technologists' and others applying tech to critical societal areas, from hospital data to policing to public engagement, risk introducing novel negative externalities in their attempts to 'change the world'. More and more people are paying attention to the negative externalities that tech itself brings to our lives."
name = "Externalities of tech"
