category = "Ethical tech"
description = "The cooperative organizational model has been around for centuries. Platform coops offer an alternative to extractive gig-economy labor platforms by providing workers with equity in the platform and/or decision-making power."
name = "Platform coops"
