category = "Tech for public challenges"
description = "Tech and meta-organizations that support the mission of non-profits and charities. Includes mainstream productivity software (like LibreOffice) as well as non-profit-specific tech (like donation management software)."
name = "Nonprofit tech"
