category = "Open innovation"
description = "The challenge model of innovation became popular in recent years due to its perceived effectiveness in spurring innovation. The challenges are usually open to all, in the hopes that the challenge program itself will generate increased interest in the problem area from a variety of potential innovators."
name = "Challenges"
