category = "Open innovation"
description = "Expert networks promise to connect decision-makers like government officials with subject matter experts who can contribute their knowledge toward improved outcomes."
name = "Expert networks"
