category = "Open civic data"
description = "Web-based data access, publishing, and distribution platforms. Open data publishing platforms are usually designed for re-use by others (Socrata, CKAN)."
name = "Open data publishing platforms"
