category = "Communicating with the people"
description = "Governmental notifications pushed to residents, often municipal government notifying its residents about local service issues."
name = "Service alerts"
