category = "Civic data"
description = 'Platforms that allow a variety of people to contribute data to a common collection. See also: Participatory Sensing, "an approach to data collection and interpretation in which individuals, acting alone or in groups, use their personal mobile devices and web services to systematically explore interesting aspects of their worlds ranging from health to culture." - IDS UCLA'
name = "Crowdsourcing"
