category = "Civic data"
description = 'Data science is used to "unify statistics, data analysis, machine learning and their related methods" to "understand and analyze actual phenomena" using data. (Hayashi, Chikio, 1996. "What is Data Science? Fundamental Concepts and a Heuristic Example").'
name = "Data science for social good"
