category = "User research"
description = "As civic tech mostly aims to promote citizen participation, usability testing services are really useful to encourage that desired engagement. Here you will learn about platforms that connect communities with the private and public sectors as well as research initiatives that involve users in design and development processes."
name = "User research groups"
