display_name = "Punjab 160009  Phone: 7087555556  Website: https://www.hairdoctors.in/hair-transplant-chandigarh/   Map: https://goo.gl/maps/XvsgkrrtMMWftHKd6"
id = "punjab_160009_phone--7087555556_website--https--www"
