display_name = "You can always visit our Hair Transplant clinic in Chandigarh:                                         Address: SCO 172-173"
id = "you_can_always_visit_our_hair_transplant_clinic_in_chandigarh--address--sco_172-173-2"
