category = "Active battles"
description = "Information on bills, legislative processes, regulatory requirements, acts, and reports in areas like digitization, participation, civic engagement."
name = "Civic tech legislation and policy"
