category = "Active battles"
description = "Educative resources to dive deep into the effects of gerrymandering and to understand how to ensure both fair redistricting and legal protections."
name = "Computer-assisted gerrymandering"
