category = "Active battles"
description = "IT-platforms made to help governments and organizations launch services and apps, customize city portals, and create websites."
name = "Government tech capacity"
