display_name = "Civic Tech"
id = "civic-tech"
synonyms = ["civic-apps", "civic-apps-team","civic-data", "civic-hacking", "civic-infrastructure", "civic-innovation", "civic-tech", "civic-tech-puerto-rico", "civictech", "civictechindex", "govtech"]
