display_name = "Democracy & Politics"
id = "democracy-politics"
synonyms = [
  "access-to-information",
  "campaign",
  "campaign-finance",
  "campaign-finance-data",
  "Campaign Finance Reform",
  "democracy",
  "democracy",
  "democratic-discourse",
  "Democratic Party",
  "Democratic Party",
  "digital-democracy",
  "edemocracy",
  "Elected Positions",
  "everypolitician",
  "freedom-of-information",
  "Gerrymandering",
  "legislation",
  "legislative-bill-analysis",
  "legislators",
  "lobbying-filings",
  "lobbyist-lookup",
  "participatory-democracy",
  "Party Politics",
  "policing",
  "policy",
  "politicians",
  "Politics",
  "representatives",
  "Republican Party",
  "track-politicians"
]
