display_name = "Education"
id = "education"
synonyms = [
  "academy",
  "academy-africa",
  "After-school Programs",
  "education",
  "educational-technology",
  "elementary-school-kids",
  "Learning",
  "learning Environment",
  "schools",
  "school-website",
  "teaching"
]
