display_name = "Education"
id = "education"
synonyms = ["academy", "academy-africa", "After-school Programs", "educational-technology", "elementary-school-kids", "education", "educational-technology", "Learning", "learning Environment", "schools", "school-website", "teaching"]
