display_name = "Environment"
id = "environment"
synonyms = [
  "air",
  "air-inequality",
  "air-pollution",
  "air-quality",
  "air-quality-data",
  "air-quality-measurements",
  "air-quality-monitor",
  "air-quality-sensor",
  "climate",
  "climate-change",
  "disaster-relief",
  "distaster-response",
  "doppler-maps",
  "drought",
  "dynamite-fishing",
  "earthquakes",
  "emergency-management",
  "emergency-response",
  "Energy",
  "Energy Efficiency",
  "environment",
  "Environmentalism",
  "environmental-justice",
  "extreme-weather",
  "flooding",
  "Garbage",
  "global-warming",
  "greenalert",
  "greenelab",
  "greenspace",
  "green-spaces",
  "litter",
  "metereological",
  "metereological-data",
  "metereology",
  "nature",
  "renewable energy",
  "renewable-energy",
  "Sanitation",
  "sea-level-rise",
  "sea-sensors",
  "smart city",
  "storm-watch",
  "stormwater",
  "sustainability",
  "trash",
  "water",
  "waterquality",
  "water resources",
  "Watershed",
  "weather"
]
