display_name = "Government"
id = "government"
synonyms = [
  "federal-websites",
  "gov",
  "governance",
  "government",
  "government-data",
  "government-procurement",
  "government-spending",
  "govtech",
  "open-budgets",
  "open-contracting",
  "opengov",
  "open-government",
  "opengovernment",
  "parliament",
  "parliamentary-monitoring"
]
