display_name = "Health Care"
id = "healthcare"
synonyms = ["cognoma", "disease-surveillance", "dodgy-doctors", "epidemics", "epidemiology", "health", "health-care", "health-resource", "healthcare", "healthtools", "healthtools-api", "healthtools-kenya-api", "hospital-services", "medicine-prices", "Opioid Crisis", "pandemic", "Public Health", "Public Heath", "public-health", "west-nile-virus", "calorie-calculator", "Cancer"]
