display_name = "Justice"
id = "justice"
synonyms = [
  "access2justice",
  "Anti-Prisons",
  "Bail Reform",
  "courtbook",
  "courtbot",
  "courtbot-python",
  "courtbot-ui",
  "court-reminder",
  "Crime",
  "Crime Mapping",
  "criminal-justice",
  "Criminal Justice Reform",
  "Criminal Records",
  "criminal-sentences",
  "expungement",
  "Incarceration",
  "Injustice",
  "justice",
  "legal",
  "legal-support",
  "Pardon",
  "philadelphia-traffic-court",
  "prison",
  "record-clearance",
  "record-expungement",
  "Transformative-Justice"
]
