display_name = "Labor"
id = "labor"
synonyms = ["workforce-development", "social-workers", "labor", "labour", "equal-pay", "fighting poverty", "living-wage", "ancir", "domestic-workers", "employment", "unemployment", "jobs", "jobsearch"]
