display_name = "Labor"
id = "labor"
synonyms = [
  "ancir",
  "domestic-workers",
  "employment",
  "equal-pay",
  "fighting poverty",
  "jobs",
  "jobsearch",
  "labor",
  "labour",
  "living-wage",
  "social-workers",
  "unemployment",
  "workforce-development"
]
