category = "Narrative tech"
description = """
"Stories are the mosaic tiles that make up deep narratives. The key role stories play in disseminating deep narratives give story tech a place in the narrative tech spectrum. When we talk about "story tech" we’re thinking of storybanks, audio and podcasting tools to share and tell immersive stories."

- Narrative Initiative"""
name = "Story tech"
