category = "Fieldwide resources"
description = "Funders offer both regular and one-off prizes to recognize and fund civic tech and its practitioners. These are usually granted for work already done, whereas the Challenges category sets a goal and offers to reward those who meet it."
name = "Awards and prizes"
