category = "Emerging Tech report"
description = '<span style="color: #ffffff;">Forty-nine tools anyone can use to leverage emerging tech for the public good. This collection includes mainstream commercial products as well as explicitly pro-social offerings. These tools were compiled while researching the <a href="https://civictech.guide/emtech">Pathways Through the Portal</a> report.</span>'
name = "Emerging Tech Tools"
