category = "Get funding"
description = "These are broader efforts by foundations to create or re-shape entire fields with dedicated waves of funding. A historic example is the Ford Foundation's popularization of legal clinics at law schools to provide pro bono services to the poor."
name = "Foundation initiatives"
