category = "Get funding"
description = "This is our collection of fundraising tech. The nearly 40 tools and platforms here seek to reinvent donation solicitation and collection, employee matching of funds, and other aspects of getting money in the door."
name = "Fundraising"
