category = "Get funding"
description = "This is our growing list of funders and donors that have supported civic tech efforts over the years. Not all fund exclusively civic tech, but if they're in this collection, they either currently support this work or have at some point in the past."
name = "Funders & donors"
