category = "Meet the others"
description = "Peer networks allow you to collaborate with others, share ideas, and work together for a common interest or cause. Check them out and see how to experiment, research, and achieve concrete actions."
name = "Peer networks"
