category = "Meet the others"
description = "Formal professional networks for people working in public engagement, civic tech, public interest tech, or related areas."
name = "Professional associations"
