category = "Meet the others"
description = "Unsurprisingly, much of the civic tech community's interactions take place remotely and asynchronously, on Slacks and listservs and forums."
name = "Socialize online"
