category = "The People"
description = """
Demonstrating impact in the civic tech field can be hard. In this section of the guide, you will find tools that can be used by governments, organizations and communities to track performance, collect data and manage impact. In addition to resources for building monitoring and evaluating systems, you can explore databases to analyze public policy or researches on how entities and nonprofits that use tech and data are generating positive effects.

&nbsp;"""
name = "Evaluate impact"
