category = "The People"
description = "Different resources and tools that can be used broadly by civic tech practitioners including opportunities to fund civic tech projects, awards, community surveys, and calendars of relevant events."
name = "Fieldwide resources"
