category = "The People"
description = "Get your start in civic tech, or change jobs and careers, with the many fellowships, jobs, and career resources available here. Or, find someone to join your team."
name = "Find a job or hire someone"
