category = "The People"
description = "This category collects different learning resources about civic tech. You can find from blogs that explain how to enhance the relationship between people and governments to podcasts and films on how humanitarian organizations are responding to crises. The collection also includes books, newsletters, research, catalogs, reports, and information about courses, trainings, and workshops."
name = "Learn about civic tech"
