category = "Fight disinformation"
description = "Factchecking is a longstanding approach to fighting disinformation, where individual claims, speeches, and rumors can be researched and verified or debunked."
name = "Factchecking"
