category = "Socialize online"
description = "This category refers to active alliances and partner programs that share expertise and support each other to accelerate change."
name = "Partner networks"
