category = "Engagement journalism"
description = "Tools and platforms that connect news audiences to constructive actions they can take based on a story. These projects sometimes struggle to gain traction in newsrooms due to their editorial concerns about objectivity, or what some observers have noted as a bias toward reporting on problems rather than solutions."
name = "News to action"
