category = "Engagement journalism"
description = "Solutions journalism is focused on highlighting solutions to the world's problems, rather than just reporting on them."
name = "Solutions journalism"
