category = "Specific campaigns"
description = "Art can help you to navigate a particular problem, reflect, analyze and find inspiration. This category presents some artistic examples, exhibits and creative works that show how technology could be used to promote change."
name = "Artistic interventions"
