category = "Specific campaigns"
description = "Campaigns that leverage corporate sensitivity to their brand reputations to drive change. Brand organizing usually works best when targeting consumer brands."
name = "Brand organizing"
