category = "Specific campaigns"
description = "Official campaign apps allow supporters to take a range of actions and coordinate directly with the campaign. Here, we present a small selection."
name = "Official campaign apps"
